version: '3'
services:
  api:
    build: './'
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./environment
    volumes:
      - ./src:/usr/src/app/src:cached
    ports:
      - 8888:80
      - 9229:9229

  mongo:
    image: 'mongo:latest'
    logging:
      driver: none
    ports:
      - 27017:27017
