# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ParkingApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for ParkingApp
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'

  target 'ParkingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ParkingApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParkingApp-tvOS

  target 'ParkingApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
